title: jeketnunc
author: mathMakesArt
email: mathmakesart@gmail.com
description: > # this means to ignore newlines
  jeketnunc is a theme for Jekyll websites,
  specifically designed for use by artists
  on the HicEtNunc platform
# social links
github_username:  mathMakesArt
twitter_username: mathMakesArt
instagram_username: mathMakesArt
facebook_username: mathMakesArt


# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
 
 # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - ignore/
